{{- if eq .Params.createOperatorServiceAccount "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-{{ .Params.operatorServiceAccountName }}
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Name }}-{{ .Params.operatorServiceAccountName }}
    app.kubernetes.io/instance: {{ .Name }}
{{- end }}
