{{- if eq .Params.createSparkServiceAccount "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Name }}-{{ .Params.sparkServiceAccountName }}
  {{- if (ne .Params.sparkJobNamespace "") }}
  namespace: {{ .Params.sparkJobNamespace }}
  {{- else }}
  namespace: {{ .Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Name }}-{{ .Params.sparkServiceAccountName }}
    app.kubernetes.io/instance: {{ .Name }}
{{- end }}
