{{- if .Params.createSparkServiceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Params.sparkServiceAccountName }}
  {{- if (ne .Params.sparkJobNamespace "") }}
  namespace: {{ .Params.sparkJobNamespace }}
  {{- else }}
  namespace: {{ .Namespace }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .OperatorName }}
    app.kubernetes.io/instance: {{ .Name }}
  {{- end }}
