{{- if .Params.enableHistoryServer }}
kind: Service
apiVersion: v1
metadata:
  name: history-server
  namespace: {{ .Namespace }}
  labels:
    app.kubernetes.io/name: history-server
    app.kubernetes.io/instance: {{ .Name }}
spec:
  ports:
  - port: 18080
    name: history-server
  selector:
    app.kubernetes.io/name: history-server
    app.kubernetes.io/instance: {{ .Name }}
    app.kubernetes.io/version: {{ .Params.operatorVersion }}
{{- end }}
