apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: shuffle-app
spec:
  schedule: "@every 3m"
  concurrencyPolicy: Forbid
  successfulRunHistoryLimit: 3
  failedRunHistoryLimit: 10
  template:
    type: Scala
    mode: cluster
    image: mesosphere/spark:spark-3.0.0-hadoop-2.9-k8s
    imagePullPolicy: Always
    mainClass: ShuffleApp
    mainApplicationFile: "https://kudo-spark.s3-us-west-2.amazonaws.com/spark-scala-tests-3.0.0-20200819.jar"
    arguments:
      - "5"
      - "4000"
      - "100000"
      - "5"
    sparkConf:
      "spark.scheduler.maxRegisteredResourcesWaitingTime": "3m"
      "spark.scheduler.minRegisteredResourcesRatio": "1"
      "spark.kubernetes.submission.connectionTimeout": "60000"
      "spark.kubernetes.submission.requestTimeout": "60000"
    sparkVersion: 3.0.0
    restartPolicy:
      type: Never
    driver:
      cores: 1
      memory: "512m"
      labels:
        version: 3.0.0
        metrics-exposed: "true"
      serviceAccount: spark-driver
    executor:
      cores: 1
      instances: 5
      memory: "512m"
      deleteOnTermination: false
      labels:
        version: 3.0.0
        metrics-exposed: "true"
    monitoring:
      exposeDriverMetrics: true
      exposeExecutorMetrics: true
      prometheus:
        jmxExporterJar: "/prometheus/jmx_prometheus_javaagent-0.11.0.jar"
        port: 8090
