{
 "title": "Spark Application",
 "description": "Spark Metrics Detailed per Job",
 "tags": [
  "Spark",
  "internal",
  "prometheus",
  "monitoring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "app_id",
    "label": "Spark App",
    "query": "label_values(kube_pod_labels, label_sparkoperator_k8s_io_app_name)"
   }
  ]
 },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(spark_executor_runtime_count{app_id=\"$app_id\"})"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (spark_executor_threadpool_activetasks{app_id=\"$app_id\"})"
    }
   ]
  },
  {
   "title": "Executors Utilization",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (spark_executor_threadpool_activetasks{app_id=\"$app_id\"}) / count(spark_executor_runtime_count{app_id=\"$app_id\"})"
    }
   ]
  },
  {
   "title": "Completed Tasks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max (spark_executor_threadpool_completetasks{app_id=\"$app_id\"})"
    }
   ]
  },
  {
   "title": "Executors (by host)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (spark_executor_runtime_count{app_id=\"$app_id\"}) by (instance)",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(spark_executor_runtime_count{app_id=\"$app_id\"})",
     "legendFormat": "TOTAL"
    }
   ]
  },
  { "title": "Runtime Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Executor Runtime by Host",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (rate({app_id=\"$app_id\",__name__=\"spark_executor_runtime_count\"}[5m])) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Executor Runtime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_runtime_count\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor CPU Runtime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_cputime_count\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor GC Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_jvmgctime_count\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Runtime",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_runtime_count\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor CPU TIme",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_cputime_count\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "JVM Heap Non-Heap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "JVM Heap Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_heap_committed\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_non_heap_committed\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_heap_used\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_non_heap_used\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "JVM Direct Capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_direct_capacity\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Total Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_total_committed\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Total Init",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_total_init\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Direct Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_direct_used\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Direct Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_direct_count\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Total Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_total_used\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVM Total Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_jvm_total_max\"}",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "Shuffle", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Shuffle Fetch Wait Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflefetchwaittime_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Write Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 46 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflewritetime_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Bytes Written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflebyteswritten_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Remote Bytes Read to Disk",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shuffleremotebytesreadtodisk_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Records Written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflerecordswritten_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Remote Bytes Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shuffleremotebytesread_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Remote Blocks Fetched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shuffleremoteblocksfetched_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Total Bytes Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shuffletotalbytesread_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Records Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflerecordsread_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Local Bytes Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflelocalbytesread_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Local Blocks Fetched",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_shufflelocalblocksfetched_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "Serialization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Executor Result Serialization Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_resultserializationtime_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Deserialization Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_deserializetime_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Deserialization CPU Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 74 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_deserializecputime_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "Data Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Bytes Written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_byteswritten_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  {
   "title": "Bytes Read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_bytesread_count\"}[5m])",
     "legendFormat": "exec-{{executor_id}}"
    }
   ]
  },
  { "title": "Executors Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 93 } },
  {
   "title": "Thread-pool: Active Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({app_id=\"$app_id\",__name__=\"spark_executor_threadpool_activetasks\"})",
     "legendFormat": "Total",
     "target": "aliasByNode(spark.{$app_id}.*.executor.threadpool.activetasks, 2, -1)"
    }
   ]
  },
  {
   "title": "Thread-pool: Completed Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(rate({app_id=\"$app_id\",__name__=\"spark_executor_threadpool_completetasks\"}[5m]))",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.threadpool.completetasks, 2, -1)"
    }
   ]
  },
  {
   "title": "Thread-pool: Max Pool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_threadpool_maxpool_size\"}",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.threadpool.maxPool_size, 2, -1)"
    }
   ]
  },
  {
   "title": "Thread-pool: Current Pool Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 94 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{app_id=\"$app_id\",__name__=\"spark_executor_threadpool_currentpool_size\"}",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.threadpool.currentPool_size, 2, -1)"
    }
   ]
  },
  { "title": "Executors FS Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "Read Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 102 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_file_read_bytes\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.file.read_bytes, 2, -1)"
    }
   ]
  },
  {
   "title": "Write  Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 102 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_file_write_bytes\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.file.read_bytes, 2, -1)"
    }
   ]
  },
  {
   "title": "Read Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_file_read_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.file.read_bytes, 2, -1)"
    }
   ]
  },
  {
   "title": "Write Ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 102 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_file_write_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.file.read_bytes, 2, -1)"
    }
   ]
  },
  { "title": "Executors FS HDFS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Read Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 110 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_hdfs_read_bytes\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.hdfs.read_bytes, 2, -1)"
    }
   ]
  },
  {
   "title": "Write Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 110 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_hdfs_write_bytes\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.hdfs.write_bytes, 2, -1)"
    }
   ]
  },
  {
   "title": "Read OPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 110 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_hdfs_read_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.hdfs.read_ops, 2, -1)"
    }
   ]
  },
  {
   "title": "Write OPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 110 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_hdfs_write_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.hdfs.write_ops, 2, -1)"
    }
   ]
  },
  { "title": "Executors FS LargeIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "HDFS Large Read OPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 118 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_hdfs_largeread_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.hdfs.largeRead_ops, 2, -1)"
    }
   ]
  },
  {
   "title": "Files Large Read OPs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 118 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate({app_id=\"$app_id\",__name__=\"spark_executor_filesystem_file_largeread_ops\"}[5m])",
     "legendFormat": "exec-{{executor_id}}",
     "target": "aliasByNode(spark.{$app_id}.*.executor.filesystem.file.largeRead_ops, 2, -1)"
    }
   ]
  }
 ]
}