{{- if eq .Params.enableMetrics "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: prometheus-operator
    release: prometheus-kubeaddons
  name: spark-cluster-monitor
spec:
  endpoints:
    - interval: {{ .Params.metricsPollingInterval }}
      port: metrics
  selector:
    matchLabels:
      spark/servicemonitor: "true"
{{- end }}