{{- if eq .Params.createRBAC "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .OperatorName }}-cr
  labels:
    app.kubernetes.io/name: {{ .OperatorName }}
    app.kubernetes.io/instance: {{ .Name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["services", "configmaps", "secrets"]
  verbs: ["create", "get", "delete", "update"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["create", "get", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "update", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["create", "get", "update", "delete"]
- apiGroups: ["sparkoperator.k8s.io"]
  resources: ["sparkapplications", "scheduledsparkapplications", "sparkapplications/status", "scheduledsparkapplications/status"]
  verbs: ["*"]
  {{- if eq .Params.enableBatchScheduler "true" }}
  # This api resources below is configured for the `volcano` batch scheduler.
- apiGroups: ["scheduling.incubator.k8s.io", "scheduling.sigs.dev"]
  resources: ["podgroups"]
  verbs: ["*"]
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .OperatorName }}-crb
  labels:
    app.kubernetes.io/name: {{ .OperatorName }}
    app.kubernetes.io/instance: {{ .Name }}
subjects:
  - kind: ServiceAccount
    {{- if eq .Params.createOperatorServiceAccount "true" }}
    name: {{ .Name }}-{{ .Params.operatorServiceAccountName }}
    {{- else }}
    name: {{ .Params.operatorServiceAccountName }}
    {{- end }}
    namespace: {{ .Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .OperatorName }}-cr
  apiGroup: rbac.authorization.k8s.io
{{- end }}
