{
 "title": "Spark Operator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_application_controller_latency_count"
    }
   ]
  },
  { "title": "Work Queue Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total number of adds handled by workqueue",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "spark_application_controller_adds",
     "legendFormat": "{{pod}"
    }
   ]
  },
  {
   "title": "Current depth of workqueue",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 9 },
   "targets": [
    {
     "expr": "spark_application_controller_depth"
    }
   ]
  },
  {
   "title": "Latency Sum",
   "type": "singlestat",
   "description": "Sum of times to complete all jobs in the period",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_application_controller_latency_sum"
    }
   ]
  },
  {
   "title": "Latency quantile for workqueue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_application_controller_latency{quantile=\"0.5\"}",
     "legendFormat": "quantile=\"0.5\""
    },
    {
     "expr": "spark_application_controller_latency{quantile=\"0.9\"}",
     "legendFormat": "quantile=\"0.9\""
    },
    {
     "expr": "spark_application_controller_latency{quantile=\"0.99\"}",
     "legendFormat": "quantile=\"0.99\""
    }
   ]
  }
 ]
}