apiVersion: apps/v1
kind: Deployment
metadata:
  name: historyserver
  namespace: spark-operator
  labels:
    app.kubernetes.io/name: historyserver
    app.kubernetes.io.version: v2.4.4-v1beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: historyserver
      app.kubernetes.io/version: v2.4.4-v1beta2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: historyserver
        app.kubernetes.io/version: v2.4.4-v1beta2
    spec:
      serviceAccountName: spark-operator-sparkoperator
      containers:
       - name: historyserver
         image: farhan5900/kudo-spark-operator:327b0d0bbc4444f01c565c02618dd90c5f2d4a03
         command: ["/opt/spark/sbin/start-history-server.sh"]
         args: ["/opt/spark/work-dir"]
         env:
          - name: SPARK_NO_DAEMONIZE
            value: "true"
         imagePullPolicy: Always
         ports:
          - containerPort: 18080
            name: "history-server"
         volumeMounts:
          - mountPath: "/opt/spark/work-dir"
            name: historyserver-storage
      volumes:
       - name: historyserver-storage
         persistentVolumeClaim:
           claimName: spark-events-pvc
