apiVersion: v1
kind: Service
metadata:
  name: spark-application-metrics
  labels:
    "spark/servicemonitor": "true"
spec:
  ports:
    - port: 8090
      name: metrics
  clusterIP: None
  selector:
    "metrics-exposed": "true"
